# Basic Jekyll configuration
title: Merlin FAREZ
description: Site personnel de Merlin FAREZ
baseurl: ""
url: "https://m-lemodi.github.io"

# Minimal setup
markdown: kramdown
plugins: []

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md